service: sls-agendamento-leve

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 3

functions:
  agendas:
    handler: src/agenda/controller/agenda-controller.handler
    description: Retorna uma lista de médicos com suas respectivas agendas e horários disponíveis.
    events:
      - http:
          path: /agendas
          method: get
          cors: true
  agendamento:
    handler: src/agendamento/controller/agendamento-controller.handler
    description: Permite que o paciente marque um horário de consulta com um médico.
    events:
      - http:
          path: /agendamento
          method: post
          cors: true

plugins:
  - serverless-offline